name: Azure Static App Deployment
on:
  push:
    branches:
      - main
      - test
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    name: Build and Deploy Job
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZ_STATIC_APP }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: 'upload'
        app_location: '/'
        output_location: 'build'
        app_build_command: 'npm run build'
        skip_api_build: true
        production_branch: 'main'
      env:
        DISABLE_JAVA_BUILD: true